# Generated by Django 4.1.4 on 2023-06-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
