# Generated by Django 4.1.4 on 2023-06-20 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_alter_clothing_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='image',
        ),
    ]
