# Generated by Django 4.1.4 on 2023-06-20 04:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_remove_clothing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image'),
        ),
    ]
